version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py test
  post_build:
    commands:
      - echo Test completed on `date`
